package com.example.focusstart.model

data class Valute(
    val AMD: Currency,
    val AUD: Currency,
    val AZN: Currency,
    val BGN: Currency,
    val BRL: Currency,
    val BYN: Currency,
    val CAD: Currency,
    val CHF: Currency,
    val CNY: Currency,
    val CZK: Currency,
    val DKK: Currency,
    val EUR: Currency,
    val GBP: Currency,
    val HKD: Currency,
    val HUF: Currency,
    val INR: Currency,
    val JPY: Currency,
    val KGS: Currency,
    val KRW: Currency,
    val KZT: Currency,
    val MDL: Currency,
    val NOK: Currency,
    val PLN: Currency,
    val RON: Currency,
    val SEK: Currency,
    val SGD: Currency,
    val TJS: Currency,
    val TMT: Currency,
    val TRY: Currency,
    val UAH: Currency,
    val USD: Currency,
    val UZS: Currency,
    val XDR: Currency,
    val ZAR: Currency
) {

    fun getCurrencies(): List<Currency> = listOf(
        AMD,
        AUD,
        AZN,
        BGN,
        BRL,
        BYN,
        CAD,
        CHF,
        CNY,
        CZK,
        DKK,
        EUR,
        GBP,
        HKD,
        HUF,
        INR,
        JPY,
        KGS,
        KRW,
        KZT,
        MDL,
        NOK,
        PLN,
        RON,
        SEK,
        SGD,
        TJS,
        TMT,
        TRY,
        UAH,
        USD,
        UZS,
        XDR,
        ZAR
    )

}